export const INDUSTRIES = [
  "Software & IT",
  "Finance & Insurance",
  "Healthcare & Life Sciences",
  "Food & Agriculture",
  "Consumer Goods",
  "Retail & E-commerce",
  "Automotive",
  "Aerospace & Defense",
  "Manufacturing & Industrial",
  "Energy & Utilities",
  "Mining & Metals",
  "Chemicals",
  "Telecommunications",
  "Logistics & Transportation",
  "Media & Entertainment",
  "Real Estate & Construction",
  "Professional Services",
  "Other",
];
