- Governance & Fairness
  - Remediation evidence — submit evidence of corrective actions; remediation is reviewed like any other evidence and may reduce a score once approved.
  - Other bullet points...