// /lib/micro-flavors.ts

/**
 * Micro-flavor text for each exact Rotten Score (0–100).
 *
 * These are intentionally opinionated, slightly dark, and
 * mix corporate satire with whistleblower energy and memes.
 */

export const FLAVOR_TEXT_BY_SCORE: Record<number, string> = {
  0: "No red flags on record. Maybe they’re actually decent.",
  1: "Cleaner than most PR statements claim to be.",
  2: "So far, so good. Almost suspiciously good.",
  3: "If there’s smoke, no one’s seen it yet.",
  4: "A couple of whispers, but nothing that smells systemic.",
  5: "Tiny scratches on an otherwise shiny halo.",
  6: "Not perfect, but clearly trying to be okay.",
  7: "A few eyebrow raises, no pitchforks yet.",
  8: "Some mild grumbling in the background, nothing explosive.",
  9: "Not spotless, but not keeping anyone up at night.",
  10: "Minor drama, the kind HR pretends is ‘fully resolved’.",
  11: "You’d still recommend a friend work here, with caveats.",
  12: "Normal corporate nonsense levels: annoying, not evil.",
  13: "Annoying policies more than actual misconduct.",
  14: "They play a bit fast and loose, but not rotten.",
  15: "More ‘meh’ than malicious right now.",
  16: "Some patterns you wouldn’t ignore, but not a crisis.",
  17: "Trust, but verify, and keep a paper trail.",
  18: "You’d join, but you’d keep your LinkedIn updated.",
  19: "Respectable on the surface, a few cracks underneath.",
  20: "This is where ‘it’s fine’ starts sounding less convincing.",
  21: "You can see the problems, but they still look fixable.",
  22: "A bit too many ‘isolated incidents’ for comfort.",
  23: "The kind of place that says ‘we’re a family’ unironically.",
  24: "Annoying enough to leave, not bad enough for a lawsuit.",
  25: "Yellow lights flashing, but not full sirens yet.",
  26: "You’d warn a friend, but not beg them to run.",
  27: "A pattern of ‘we’re sorry you feel that way’ responses.",
  28: "Just enough smoke that you start looking for fire exits.",
  29: "Too many NDAs for a company with ‘nothing to hide’.",
  30: "The vibes are off, even if the reporting isn’t heavy yet.",
  31: "This is what ‘quietly problematic’ looks like.",
  32: "Leadership says all the right words, behavior disagrees.",
  33: "You get the sense HR’s real job is containment.",
  34: "Looks good on the website, feels weird on the inside.",
  35: "There’s a reason ex-employees sound tired when they talk.",
  36: "Small fires everywhere, but nothing they can’t ignore.",
  37: "They care about optics more than people.",
  38: "Enough red flags to decorate a mid-sized parade.",
  39: "Not a disaster, but you wouldn’t bet your health on them.",
  40: "This is the ‘proceed with caution’ zone.",
  41: "If you join, do it with boundaries and backups.",
  42: "Some teams might be okay; the system clearly isn’t.",
  43: "The kind of place that calls exploitation a ‘growth opportunity’.",
  44: "Middle management is probably suffering the most here.",
  45: "Rotten pockets inside an otherwise functional shell.",
  46: "They’ve clearly chosen profit over people more than once.",
  47: "The stories coming out aren’t just one-offs anymore.",
  48: "Too many ‘learning moments’, not enough actual change.",
  49: "You can smell the rot, even if it’s not fully exposed.",
  50: "Balanced on the edge between fixable and fundamentally broken.",
  51: "This is where you start telling friends: ‘Honestly, don’t.’",
  52: "Survivable, but only if you have options and thick skin.",
  53: "The success story everyone praises, powered by people burning out.",
  54: "HR is probably exhausted from spinning this as ‘normal’.",
  55: "A case study in how not to treat workers and customers.",
  56: "Leadership slides say ‘values’; reality says ‘damage control’.",
  57: "You’d only join if backed into a financial corner.",
  58: "More red flags than a sports day at a dictatorship.",
  59: "They break things and people, then call it innovation.",
  60: "Welcome to the ‘you knew what this was’ zone.",
  61: "Glassdoor reviews probably sound like war stories.",
  62: "The kind of place whistleblowers eventually crawl out of.",
  63: "Ethical on LinkedIn, chaotic evil in the group chat.",
  64: "They fix problems only when journalists start asking questions.",
  65: "A slow-moving disaster wrapped in a glossy brand.",
  66: "Employees don’t quit, they escape.",
  67: "You don’t work here; you survive here.",
  68: "Rot baked into the business model, not just mistakes.",
  69: "Nice slogans, terrible outcomes. Classic playbook.",
  70: "This is where working here becomes a moral question.",
  71: "You’d hesitate to recommend them even to your worst ex.",
  72: "Feels less like a job, more like a damage multiplier.",
  73: "Bad enough that fixing it would require new leadership.",
  74: "You can practically hear the lawyers in every decision.",
  75: "This is ‘red flags everywhere’ territory. Sirens included.",
  76: "If there’s a crisis, odds are they caused it.",
  77: "Employees are either complicit, trapped, or leaving.",
  78: "They don’t just cross lines; they redraw them.",
  79: "People don’t leave reviews; they leave warnings.",
  80: "Welcome to the villain arc chapter of capitalism.",
  81: "You’re not just a worker here; you’re set dressing for harm.",
  82: "Ethics are treated as a branding exercise, not a constraint.",
  83: "Every quarter probably comes with a new scandal.",
  84: "Internal motto might as well be ‘don’t get caught’.",
  85: "They’d rather retaliate than reflect.",
  86: "Think ‘Empire from Star Wars’, but with worse onboarding.",
  87: "If this was a sci-fi universe, they’d be the megacorp villain.",
  88: "You don’t just do tasks; you help the machine hurt people.",
  89: "The kind of place regulators eventually raid.",
  90: "You’re basically working for the Empire’s HR department.",
  91: "If there’s a Death Star, they’re tendering for the contract.",
  92: "You clock in; your conscience clocks out.",
  93: "They treat laws like suggestions and people like consumables.",
  94: "This company is a case study waiting for a documentary.",
  95: "If hell had an enterprise partner program, they’d be platinum tier.",
  96: "You don’t need satire to describe them; reality is bad enough.",
  97: "They don’t just ignore harm; they industrialize it.",
  98: "You’d genuinely question working here, even for a lot of money.",
  99: "Satan would swipe left: ‘too intense for me, sorry.’",
  100: "If hell had a board of directors, this company would chair it.",
};
