CREATE TABLE IF NOT EXISTS public.company_slug_redirects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    old_slug text NOT NULL,
    new_slug text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.company_slug_redirects
    ADD COLUMN IF NOT EXISTS id bigint,
    ADD COLUMN IF NOT EXISTS company_id bigint,
    ADD COLUMN IF NOT EXISTS old_slug text,
    ADD COLUMN IF NOT EXISTS new_slug text,
    ADD COLUMN IF NOT EXISTS created_at timestamptz;

ALTER TABLE public.company_slug_redirects
    ALTER COLUMN company_id SET NOT NULL,
    ALTER COLUMN old_slug SET NOT NULL,
    ALTER COLUMN new_slug SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT now();

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'company_slug_redirects'
          AND column_name = 'id'
          AND is_identity = 'NO'
    ) THEN
        EXECUTE 'ALTER TABLE public.company_slug_redirects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
    END IF;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'company_slug_redirects_pkey'
    ) THEN
        ALTER TABLE public.company_slug_redirects
            ADD CONSTRAINT company_slug_redirects_pkey PRIMARY KEY (id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'company_slug_redirects_company_id_fkey'
    ) THEN
        ALTER TABLE public.company_slug_redirects
            ADD CONSTRAINT company_slug_redirects_company_id_fkey
            FOREIGN KEY (company_id)
            REFERENCES public.companies(id)
            ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'company_slug_redirects_old_slug_key'
    ) THEN
        ALTER TABLE public.company_slug_redirects
            ADD CONSTRAINT company_slug_redirects_old_slug_key UNIQUE (old_slug);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'company_slug_redirects_old_slug_not_blank'
    ) THEN
        ALTER TABLE public.company_slug_redirects
            ADD CONSTRAINT company_slug_redirects_old_slug_not_blank
            CHECK (btrim(old_slug) <> '');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'company_slug_redirects_new_slug_not_blank'
    ) THEN
        ALTER TABLE public.company_slug_redirects
            ADD CONSTRAINT company_slug_redirects_new_slug_not_blank
            CHECK (btrim(new_slug) <> '');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'company_slug_redirects_old_slug_format'
    ) THEN
        ALTER TABLE public.company_slug_redirects
            ADD CONSTRAINT company_slug_redirects_old_slug_format
            CHECK (old_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'company_slug_redirects_new_slug_format'
    ) THEN
        ALTER TABLE public.company_slug_redirects
            ADD CONSTRAINT company_slug_redirects_new_slug_format
            CHECK (new_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'company_slug_redirects_no_self_redirect'
    ) THEN
        ALTER TABLE public.company_slug_redirects
            ADD CONSTRAINT company_slug_redirects_no_self_redirect
            CHECK (old_slug <> new_slug);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS company_slug_redirects_company_id_idx
    ON public.company_slug_redirects (company_id);

CREATE INDEX IF NOT EXISTS company_slug_redirects_new_slug_idx
    ON public.company_slug_redirects (new_slug);

ALTER TABLE public.company_slug_redirects ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'company_slug_redirects'
          AND policyname = 'company_slug_redirects_public_read'
    ) THEN
        CREATE POLICY company_slug_redirects_public_read
            ON public.company_slug_redirects
            FOR SELECT
            TO anon, authenticated
            USING (true);
    END IF;
END
$$;

GRANT SELECT ON public.company_slug_redirects TO anon, authenticated;
