export const INDUSTRIES = [
  "Agriculture",
  "Automotive",
  "Construction",
  "Consumer Goods",
  "Education",
  "Energy",
  "Finance & Insurance",
  "Food & Beverage",
  "Healthcare",
  "Hospitality & Tourism",
  "Information Technology",
  "Logistics & Transportation",
  "Manufacturing",
  "Media & Entertainment",
  "Mining & Resources",
  "Pharmaceutical",
  "Real Estate",
  "Retail",
  "Telecommunications",
  "Utilities",
  "Other",
];

export const EMPLOYEE_RANGES: { label: string; min: number }[] = [
  { label: "1-10", min: 1 },
  { label: "11-50", min: 11 },
  { label: "51-200", min: 51 },
  { label: "201-500", min: 201 },
  { label: "501-1000", min: 501 },
  { label: "1001-5000", min: 1001 },
  { label: "5001-10000", min: 5001 },
  { label: "10001+", min: 10001 },
];
